export default {
  "Afrikaans - South Africa": "af-ZA",
  "Arabic - Algeria": "ar-DZ",
  "Arabic - Bahrain": "ar-BH",
  "Arabic - Egypt": "ar-EG",
  "Arabic - Israel": "ar-IL",
  "Arabic - Iraq": "ar-IQ",
  "Arabic - Jordan": "ar-JO",
  "Arabic - Kuwait": "ar-KW",
  "Arabic - Lebanon": "ar-LB",
  "Arabic - Morocco": "ar-MA",
  "Arabic - Oman": "ar-OM",
  "Arabic - Palestinian Territory": "ar-PS",
  "Arabic - Qatar": "ar-QA",
  "Arabic - Saudi Arabia": "ar-SA",
  "Arabic - Tunisia": "ar-TN",
  "Arabic - UAE": "ar-AE",
  "Basque - Spain": "eu-ES",
  "Bulgarian - Bulgaria": "bg-BG",
  "Catalan - Spain": "ca-ES",
  "Chinese Mandarin - China (Simp.)": "cmn-Hans-CN",
  "Chinese Mandarin - Hong Kong SAR (Trad.)": "cmn-Hans-HK",
  "Chinese Mandarin - Taiwan (Trad.)": "cmn-Hant-TW",
  "Chinese Cantonese - Hong Kong": "yue-Hant-HK",
  "Croatian - Croatia": "hr_HR",
  "Czech - Czech Republic": "cs-CZ",
  "Danish - Denmark": "da-DK",
  "English - Australia": "en-AU",
  "English - Canada": "en-CA",
  "English - India": "en-IN",
  "English - Ireland": "en-IE",
  "English - New Zealand": "en-NZ",
  "English - Philippines": "en-PH",
  "English - South Africa": "en-ZA",
  "English - United Kingdom": "en-GB",
  "English - United States": "en-US",
  "Farsi - Iran": "fa-IR",
  "French - France": "fr-FR",
  "Filipino - Philippines": "fil-PH",
  "Galician - Spain": "gl-ES",
  "German - Germany": "de-DE",
  "Greek - Greece": "el-GR",
  "Finnish - Finland": "fi-FI",
  "Hebrew - Israel": "he-IL",
  "Hindi - India": "hi-IN",
  "Hungarian - Hungary": "hu-HU",
  "Indonesian - Indonesia": "id-ID",
  "Icelandic - Iceland": "is-IS",
  "Italian - Italy": "it-IT",
  "Italian - Switzerland": "it-CH",
  "Japanese - Japan": "ja-JP",
  "Korean - Korea": "ko-KR",
  "Lithuanian - Lithuania": "lt-LT",
  "Malaysian - Malaysia": "ms-MY",
  "Dutch - Netherlands": "nl-NL",
  "Norwegian - Norway": "nb-NO",
  "Polish - Poland": "pl-PL",
  "Portuguese - Brazil": "pt-BR",
  "Portuguese - Portugal": "pt-PT",
  "Romanian - Romania": "ro-RO",
  "Russian - Russia": "ru-RU",
  "Serbian - Serbia": "sr-RS",
  "Slovak - Slovakia": "sk-SK",
  "Slovenian - Slovenia": "sl-SI",
  "Spanish - Argentina": "es-AR",
  "Spanish - Bolivia": "es-BO",
  "Spanish - Chile": "es-CL",
  "Spanish - Colombia": "es-CO",
  "Spanish - Costa Rica": "es-CR",
  "Spanish - Dominican Republic": "es-DO",
  "Spanish - Ecuador": "es-EC",
  "Spanish - El Salvador": "es-SV",
  "Spanish - Guatemala": "es-GT",
  "Spanish - Honduras": "es-HN",
  "Spanish - MÃ©xico": "es-MX",
  "Spanish - Nicaragua": "es-NI",
  "Spanish - PanamÃ¡": "es-PA",
  "Spanish - Paraguay": "es-PY",
  "Spanish - PerÃº": "es-PE",
  "Spanish - Puerto Rico": "es-PR",
  "Spanish - Spain": "es-ES",
  "Spanish - Uruguay": "es-UY",
  "Spanish - United States": "es-US",
  "Spanish - Venezuela": "es-VE",
  "Swedish - Sweden": "sv-SE",
  "Thai - Thailand": "th-TH",
  "Turkish - Turkey": "tr-TR",
  "Ukrainian - Ukraine": "uk-UA",
  "Vietnamese - Viet Nam": "vi-VN",
  "Zulu - South Africa": "zu-ZA"
};
